### ISSUE TITLE
Error loading shared library libcrypto.so.1.0.0

### ISSUE THREAD

**Issue by alwaystest** [hangim/shadowsocks-docker#4]
Supervisor log said that:

> gave up: ss-server entered FATAL state, too many start retries too quickly

So i tried to run ss-server manually, but i got this error:

> Error loading shared library libcrypto.so.1.0.0: No such file or directory (needed by /usr/local/bin/ss-server)

**Comment by alwaystest** [comment]
I tried `FROM alpine:3.4` and it works fine.

**Comment by pdszhh** [comment]
revert for more test

**Comment by pdszhh** [comment]
fixed https://github.com/hangim/shadowsocks-docker/commit/887e98ab4d800027215b72437b3632866864b8aa

because alpine 3.5 switched from OpenSSL to LibreSSL，see https://www.alpinelinux.org/posts/Alpine-3.5.0-released.html

**Comment by alwaystest** [comment]
能否请教一下为什么alpine 3.5更换了SSL库就导致找不到libcrypto.so吗？OpenSSL在alpine 3.5上也是可以安装的呀。还有编译SS需要安装的库是从哪里看出来的？谢谢。

**Comment by pdszhh** [comment]
In this commit https://github.com/hangim/shadowsocks-docker/commit/05bb71605876ba987be3e2223ecc62673a7dcbba and before.

Use **openssl-dev** to compile *shadowsocks-libev*, and then remove **openssl-dev** to reduce docker image size. 

So *shadowsocks-libev* dependence **openssl** to running, but alpine 3.5 don't have it as default and i didn't install it.

You can install **openssl** manual to solve this problem.

change

    apk add --no-cache --virtual .run-deps pcre

to

    apk add --no-cache --virtual .run-deps pcre openssl

If you dont want to install **openssl**, you can use **libressl-dev** to compile *shadowsocks-libev*, alpine 3.5 have **liberssl** to ensure *shadowsocks-libev* running as normal, just like https://github.com/hangim/shadowsocks-docker/commit/887e98ab4d800027215b72437b3632866864b8aa

As the second question, please see https://github.com/shadowsocks/shadowsocks-libev
